version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml/models:/app/ml/models
      - ./ml/vectorizers:/app/ml/vectorizers
      - ./ml/logs:/app/ml/logs
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:8000
      - PYTHONPATH=/app
    volumes:
      - ./reports:/app/reports
    depends_on:
      - backend
    restart: always
